all:
mxpr:adj_matrix_pointer_time.cpp
	g++ -o bipartite adj_matrix_pointer_time.cpp
	./bipartite
mx:adj_matrix_time.cpp
	g++ -o bipartite adj_matrix_time.cpp
	./bipartite
ls:adj_list_time.cpp
	g++ -o bipartite adj_list_time.cpp
	./bipartite
lspr:adj_list_pointer_time.cpp
	g++ -o bipartite adj_list_pointer_time.cpp
	./bipartite
.PHONY:clean
clean:
	rm -rf *.o bipartite